version: '3.8'

services:
    dev:
        build:
            context: ./.devcontainer
            dockerfile: Dockerfile
        container_name: online-menu
        volumes:
            - .:/development
        command: sleep infinity
        networks:
            online-menu-nt:

    frontend:
        image: online-menu-frontend
        container_name: frontend-container
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - BUILD_CONTEXT=frontend
                - BUILD_PORT=3000
        volumes:
            - .:/online-menu/
        command:
            - yarn
            - dev:f
        depends_on:
            - backend
        ports:
            - '3001:3000'
        networks:
            online-menu-nt:

    backend:
        image: online-menu-backend
        container_name: backend-container
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - BUILD_CONTEXT=backend
                - BUILD_PORT=4000
        volumes:
            - .:/online-menu/
        command:
            - yarn
            - dev:b

        ports:
            - '8081:4000'
        networks:
            online-menu-nt:
            db_nt:
networks:
    online-menu-nt:
        driver: 'bridge'
        ipam:
            config:
                - subnet: 178.24.0.0/16
                  gateway: 178.24.0.1
    db_nt:
        external: true
