version: '3.8'

services:
  dev:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    container_name: menu-store
    volumes:
      - .:/development
    command: sleep infinity
    networks: 
      menu-store-nt:

  frontend:
    image: menu-store-frontend
    container_name: menu-store-frontend-container
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=menu-store-frontend
    volumes:
      - .:/menu-store/
    command:
      - yarn
      - dev:frontend
    depends_on:
      - backend
    ports:
      - "3000:8080"
    networks:
      menu-store-nt:

  backend:
    image: menu-store-backend
    container_name: menu-store-backend-container
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=menu-store-backend
    volumes:
      - .:/menu-store/
    command:
      - yarn
      - dev:backend
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    networks:
      menu-store-nt:

  mysql-db: 
    image: mysql:8.0.28-oracle
    container_name: menu-store-mysql-container
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    restart: always
    networks: 
      menu-store-nt:
    environment:
      MYSQL_ROOT_PASSWORD: "pass_test"
networks: 
  menu-store-nt: 
    driver: "bridge"
    ipam:
      config:
        - subnet: 178.24.0.0/16
          gateway: 178.24.0.1