version: '3.8'

services:
  my-dev:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16-bullseye
    container_name: menu-store
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks: 
      menu-store-nt:

  frontend:
    image: menu-store-frontend
    container_name: menu-store-frontend-container
    tty: true
    build:
      context: ../menu-store-frontend
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      menu-store-nt:

  backend:
    image: menu-store-backend
    container_name: menu-store-backend-container
    tty: true
    build:
      context: ../menu-store-backend
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    networks:
      menu-store-nt:

  mysql-db: 
    image: mysql:8.0.28-oracle
    container_name: menu-store-mysql-container
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    restart: always
    networks: 
      menu-store-nt:
    environment:
      MYSQL_ROOT_PASSWORD: "pass_test"

networks: 
  menu-store-nt: 
    driver: "bridge"
    ipam:
      config:
        - subnet: 178.23.0.0/16
          gateway: 178.23.0.1